hollymovies/urls.py
from django.conf.urls.static import static
from django.contrib import admin
#from django.contrib.auth.views import LoginView
from django.urls import path, include

from api.views import *
from accounts.views import SignUpView, user_logout
from hollymovies import settings
from viewer.views import home, MoviesListView, \
    CreatorsListView, creator, GenreView, CountryView, CreatorCreateView, CreatorUpdateView, \
    CreatorDeleteView, MovieCreateView, MovieUpdateView, MovieDeleteView, GenreCreateView, GenreUpdateView, \
    GenreDeleteView, CountryCreateView, CountryUpdateView, CountryDeleteView, GenresListView, CountriesListView, \
    ProfilesListView, ImageCreateView, ImageDetailView, ImagesListView, ImageUpdateView, ImageDeleteView, \
    MovieTemplateView, ReviewDeleteView, search

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),

    path('', home, name='home'),

    path('movies/', MoviesListView.as_view(), name='movies'),
    path('movie/create/', MovieCreateView.as_view(), name='movie_create'),
    path('movie/update/<pk>/', MovieUpdateView.as_view(), name='movie_update'),
    path('movie/delete/<pk>/', MovieDeleteView.as_view(), name='movie_delete'),
    path('movie/<pk>/', MovieTemplateView.as_view(), name='movie'),

    path('creators/', CreatorsListView.as_view(), name='creators'),
    path('creator/create/', CreatorCreateView.as_view(), name='creator_create'),
    path('creator/update/<pk>/', CreatorUpdateView.as_view(), name='creator_update'),
    path('creator/delete/<pk>/', CreatorDeleteView.as_view(), name='creator_delete'),
    path('creator/<pk>/', creator, name='creator'),

    path('gernes/', GenresListView.as_view(), name='genres'),
    path('genre/create/', GenreCreateView.as_view(), name='genre_create'),
    path('genre/update/<pk>/', GenreUpdateView.as_view(), name='genre_update'),
    path('genre/delete/<pk>/', GenreDeleteView.as_view(), name='genre_delete'),
    path('genre/<pk>/', GenreView.as_view(), name='genre'),

    path('countries/', CountriesListView.as_view(), name='countries'),
    path('country/create/', CountryCreateView.as_view(), name='country_create'),
    path('country/update/<pk>/', CountryUpdateView.as_view(), name='country_update'),
    path('country/delete/<pk>/', CountryDeleteView.as_view(), name='country_delete'),
    path('country/<pk>/', CountryView.as_view(), name='country'),

    path('images/', ImagesListView.as_view(), name='images'),
    path('image/create/', ImageCreateView.as_view(), name='image_create'),
    path('image/update/<pk>/', ImageUpdateView.as_view(), name='image_update'),
    path('image/delete/<pk>/', ImageDeleteView.as_view(), name='image_delete'),
    path('image/<pk>/', ImageDetailView.as_view(), name='image'),

    path('review/delete/<pk>/', ReviewDeleteView.as_view(), name='review_delete'),

    path('search/', search, name='search'),

    path('profiles/', ProfilesListView.as_view(), name='profiles'),

    #path('accounts/login/', LoginView.as_view(), name='login'),
    path('accounts/signup/', SignUpView.as_view(), name='signup'),
    path('accounts/logout/', user_logout, name='logout'),
    path('accounts/', include('django.contrib.auth.urls')),  # defaultní paths a veiws z Djanga

    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api/movies/', Movies.as_view(), name='api_movies'),
    path('api/movie/<pk>/', MovieDetail.as_view(), name='api_movie'),
    path('api/creators/', Creators.as_view(), name='api_creators'),
    path('api/creator/<pk>/', CreatorDetail.as_view(), name='api_creator'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

viewer/models.py
from datetime import date

from django.db.models import *  # Model, CharField, DateField, ForeignKey, SET_NULL, TextField, ManyToManyField, IntegerField

from accounts.models import Profile


class Genre(Model):
    name = CharField(max_length=20, null=False, blank=False, unique=True)

    class Meta:
        ordering = ['name']

    def __repr__(self):
        return f"Genre(name={self.name})"

    def __str__(self):
        return f"{self.name}"


class Country(Model):
    name = CharField(max_length=64, null=False, blank=False, unique=True)
    code = CharField(max_length=3, null=False, blank=False, unique=True)

    class Meta:
        verbose_name_plural = "Countries"
        ordering = ['name']

    def __repr__(self):
        return f"Country(name={self.name}, code={self.code})"

    def __str__(self):
        return f"{self.name}"


class Creator(Model):
    name = CharField(max_length=32, null=True, blank=True)
    surname = CharField(max_length=32, null=True, blank=True)
    date_of_birth = DateField(null=True, blank=True)
    date_of_death = DateField(null=True, blank=True)
    country_of_birth = ForeignKey(Country, null=True, blank=True, on_delete=SET_NULL, related_name='creators_born')
    country_of_death = ForeignKey(Country, null=True, blank=True, on_delete=SET_NULL, related_name='creators_died')
    biography = TextField(null=True, blank=True)
    created = DateTimeField(auto_now_add=True)
    updated = DateTimeField(auto_now=True)

    class Meta:
        ordering = ['surname', 'name']

    def __repr__(self):
        return f"Creator(name={self.name}, surname={self.surname})"

    def __str__(self):
        return f"{self.name} {self.surname}"

    def age(self):
        if self.date_of_birth:
            end_date = date.today()
            if self.date_of_death:
                end_date = self.date_of_death
            return (end_date.year - self.date_of_birth.year -
                    ((end_date.month, end_date.day) < (self.date_of_birth.month, self.date_of_birth.day)))
        return None


class Movie(Model):
    title_orig = CharField(max_length=150, null=False, blank=False)  # https://en.wikipedia.org/wiki/Night_of_the_Day_of_the_Dawn_of_the_Son_of_the_Bride_of_the_Return_of_the_Revenge_of_the_Terror_of_the_Attack_of_the_Evil,_Mutant,_Alien,_Flesh_Eating,_Hellbound,_Zombified_Living_Dead
    title_cz = CharField(max_length=150, null=True, blank=True)
    genres = ManyToManyField(Genre, blank=True, related_name='movies')
    countries = ManyToManyField(Country, blank=True, related_name='movies')
    actors = ManyToManyField(Creator, blank=True, related_name='acting')
    directors = ManyToManyField("viewer.Creator", blank=True, related_name='directing')
    length = IntegerField(null=True, blank=True)  # min
    released = IntegerField(null=True, blank=True)  # year
    description = TextField(null=True, blank=True)
    rating = FloatField(null=True, blank=True)  # 0-100
    created = DateTimeField(auto_now_add=True)
    updated = DateTimeField(auto_now=True)

    class Meta:
        ordering = ['title_orig', 'released']

    def __repr__(self):
        return f"Movie(title_orig={self.title_orig})"

    def __str__(self):
        return f"{self.title_orig} ({self.released})"

    def length_format(self):
        hours = self.length // 60
        minutes = self.length % 60
        if minutes < 10:
            minutes = f"0{minutes}"
        return f"{hours}:{minutes}"


class Image(Model):
    image = ImageField(upload_to='images/', default=None, null=False, blank=False)
    movie = ForeignKey(Movie, on_delete=SET_NULL, null=True, blank=True, related_name='images')
    actors = ManyToManyField(Creator, blank=True, related_name='images')
    description = TextField(null=True, blank=True)

    def __repr__(self):
        return f"Image(image={self.image}, movie={self.movie}, actors={self.actors}, description={self.description})"

    def __str__(self):
        return f"Image: {self.image}, {self.description}"


class Review(Model):
    movie = ForeignKey(Movie, on_delete=CASCADE, null=False, blank=False, related_name='reviews')
    user = ForeignKey(Profile, on_delete=SET_NULL, null=True, blank=False, related_name='reviews')
    rating = IntegerField(null=True, blank=True)
    text = TextField(null=True, blank=True)
    created = DateTimeField(auto_now_add=True)
    updated = DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-updated']

    def __repr__(self):
        return (f"Review(movie={self.movie}, user={self.user}, "
                f"rating={self.rating}, text={self.text})")

    def __str__(self):
        return f"User: {self.user}, movie:{self.movie}, rating={self.rating}, text={self.text[:50]}"

viewer/forms.py
from datetime import date

from django.core.exceptions import ValidationError
from django.forms import Form, CharField, DateField, ModelChoiceField, Textarea, ModelForm, NumberInput

from viewer.models import Country, Creator, Movie, Genre, Image, Review


class GenreModelForm(ModelForm):
    class Meta:
        model = Genre
        fields = '__all__'


class CountryModelForm(ModelForm):
    class Meta:
        model = Country
        fields = '__all__'


class MovieModelForm(ModelForm):
    class Meta:
        model = Movie
        fields = '__all__'


class CreatorModelForm(ModelForm):
    class Meta:
        model = Creator
        fields = '__all__'
        #fields = ['surname', 'name', 'date_of_birth', 'date_of_death']
        #exclude = ['date_of_death', 'name']

    date_of_death = DateField(required=False, widget=NumberInput(attrs={'type': 'date'}))
    date_of_birth = DateField(required=False, widget=NumberInput(attrs={'type': 'date'}))

    def clean_name(self):
        cleaned_data = super().clean()
        initial = cleaned_data['name']
        print(f"initial name: '{initial}'")
        result = initial
        if initial is not None:
            result = initial.strip()
            print(f"result: '{result}'")
            if len(result):
                result = result.capitalize()
            print(f"result: '{result}'")
        return result

    def clean_date_of_birth(self):
        cleaned_data = super().clean()
        date_of_birth = cleaned_data['date_of_birth']
        if date_of_birth and date_of_birth >= date.today():
            raise ValidationError('Lze zadávat datum narození pouze v minulosti')
        return date_of_birth

    def clean(self):
        cleaned_data = super().clean()
        name = cleaned_data['name']
        surname = cleaned_data['surname']
        if name is None:
            name = ''
        if surname is None:
            surname = ''
        if len(name.strip()) == 0 and len(surname.strip()) == 0:
            raise ValidationError('Je potřeba zadat jméno nebo příjmení')
        # TODO: pokud jsou zadaná data narození a úmrtí, tak datum narození musí být < datum úmrtí
        cleaned_data['name'] = name
        cleaned_data['surname'] = surname
        return cleaned_data


class ImageModelForm(ModelForm):
    class Meta:
        model = Image
        fields = '__all__'


class ReviewModelForm(ModelForm):
    class Meta:
        model = Review
        fields = ['rating', 'text']

viewer/templates/confirm_delete.html
{% extends "base.html" %}

{% block title %}
Smazat záznam
{% endblock %}

{% block content %}
    <form method="POST">
        {% csrf_token %}
        <p>Opravdu chceš smazat záznam
            {% if object.print_to_delete %}
                "{{ object.print_to_delete }}"
            {% else %}
                "{{ object }}"
            {% endif %}
            z databáze?</p>
        <input type="submit" value="Smazat" class="btn btn-danger">
        <input type="button" value="Zpět" class="btn btn-primary" onClick="javascript:history.back()">
    </form>
{% endblock %}

viewer/templates/countries.html
{% extends "base.html" %}

{% block content %}
    <h1>Země</h1>
        <ul>
        {% for country in countries %}
            <li><a href="{% url 'country' country.id %}">{{ country }}</a>
                {% if perms.viewer.change_country %}
                    <a href="{% url 'country_update' country.id %}">✏️</a>
                {% endif %}
                {% if perms.viewer.delete_country %}
                    <a href="{% url 'country_delete' country.id %}">❌</a>
                {% endif %}
            </li>
        {% endfor %}
        </ul>
{% endblock %}

viewer/templates/creator.html
{% extends "base.html" %}

{% block content %}
<h1>{{ creator.name }} {{ creator.surname }}</h1>
<div class="creator-images">
    {% for image in creator.images.all %}
        <span class="creator-image">
            <a href="{% url 'image' image.id %}">
                <img src="{{ image.image.url }}" alt="{{ image.description }}" width="150px">
            </a>
        </span>
    {% endfor %}
</div>
<div class="creator-details">
    <div class="creator-birthdate">
        <strong>Narození:</strong>
        {{ creator.date_of_birth|date:'d. m. Y' }}
        ({{ creator.country_of_birth }})
        věk: {{ creator.age }}
    </div>

    <div class="creator-deathdate">
        {% if creator.date_of_death %}
            <strong>Úmrtí:</strong>
            {{ creator.date_of_death|date:'d. m. Y' }}
            ({{ creator.country_of_death }})
        {% endif %}
    </div>

    {% if creator.directing.all %}
        <strong>Režisér:</strong>
        {% for movie in creator.directing.all %}
            <a href="{% url 'movie' movie.id %}">{{ movie }}</a>{% if not forloop.last %},{% endif %}
        {% endfor %}
    {% endif %}

    {% if creator.acting.all %}
        <strong>Herec:</strong>
        {% for movie in creator.acting.all %}
            <a href="{% url 'movie' movie.id %}">{{ movie }}</a>{% if not forloop.last %},{% endif %}
        {% endfor %}
    {% endif %}

    <div class="creator-biography">
        <strong>Biografie:</strong><br>
        {{ creator.biography }}
    </div>

    {% if perms.viewer.change_creator %}
        <a href="{% url 'creator_update' creator.id %}" class="btn btn-primary">Aktualizovat</a>
    {% endif %}
    {% if perms.viewer.delete_creator %}
        <a href="{% url 'creator_delete' creator.id %}" class="btn btn-danger">Smazat</a>
    {% endif %}
</div>
{% endblock %}

viewer/templates/creators.html
{% extends "base.html" %}

{% block content %}
    Filtr: všichni, herci, režiséři
    <h1>Tvůrci</h1>
        <ul>
        {% for creator in creators %}
            <li><a href="{% url 'creator' creator.id %}">{{ creator }}</a>
                {% if perms.viewer.change_creator %}
                    <a href="{% url 'creator_update' creator.id %}">✏️</a>
                {% endif %}
                {% if perms.viewer.delete_creator %}
                    <a href="{% url 'creator_delete' creator.id %}">❌</a>
                {% endif %}
            </li>
        {% endfor %}
        </ul>
{% endblock %}

viewer/templates/form.html
{% extends "base.html" %}

{% block title %}
HollyMovies - formulář
{% endblock %}

{% block content %}
<form method="POST">
    {% csrf_token %}
    {% comment %}{{ form }}{% endcomment %}
    <table>{{ form.as_table }}</table>
    {% comment %}{{ form.as_p }}{% endcomment %}
    {% comment %}<ul>{{ form.as_ul }}</ul>{% endcomment %}
    <input id="id_submit" type="submit" value="Uložit" class="btn btn-primary">
</form>
{% endblock %}

viewer/templates/form_image.html
{% extends "base.html" %}

{% block content %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <table>{{ form.as_table }}</table>
    <input id="id_submit" type="submit" value="Uložit" class="btn btn-primary">
</form>
{% endblock %}

viewer/templates/genres.html
{% extends "base.html" %}

{% block content %}
    <h1>Žánry</h1>
        <ul>
        {% for genre in genres %}
            <li><a href="{% url 'genre' genre.id %}">{{ genre }}</a>
                {% if perms.viewer.change_genre %}
                    <a href="{% url 'genre_update' genre.id %}">✏️</a>
                {% endif %}
                {% if perms.viewer.delete_genre %}
                    <a href="{% url 'genre_delete' genre.id %}">❌</a>
                {% endif %}
            </li>
        {% endfor %}
        </ul>
{% endblock %}

viewer/templates/hello.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Welcome to HollyMovies!</title>
</head>
<body>
<h1>Welcome to HollyMovies!</h1>
    <ul>
    {% for adjective in adjectives %}
        <li>{{ adjective }}</li>
    {% endfor %}
    </ul>
</body>
</html>

viewer/templates/home.html
{% extends "base.html" %}

{% block title %}
HollyMovies
{% endblock %}

{% block content %}
<h1>Vítejte v naší HollyMovie databázi.</h1>
{% endblock %}

viewer/templates/image.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-5">
    <span class="movie-image">
        <img src="{{ image.image.url }}" alt="{{ image.description }}" height="80%">
    </span>

    <div class="image-details mt-4">
        {% if image.movie %}
            <div class="image-movie mb-2">
                Film: <a href="{% url 'movie' image.movie.id %}">{{ image.movie.title_orig }}</a>
            </div>
        {% endif %}
        {% if image.actors.all %}
            <div class="image-actors mb-2"> Herci:
                {% for actor in image.actors.all %}
                    <span class="image-creator mb-2">
                        <a href="{% url 'creator' actor.id %}">
                            {{ actor }}</a>{% if not forloop.last %},{% endif %}
                    </span>
                {% endfor %}
            </div>
        {% endif %}
        <div class="image-description mb-2">
            Popis: {{ image.description }}
        </div>
    </div>
</div>
{% endblock %}

viewer/templates/movie.html
{% extends "base.html" %}

{% block content %}
<h1>{{ movie.title_orig }}</h1>
<div class="movie-title-cz">{{ movie.title_cz }} </div>
<div class="movie-images">
    {% for image in movie.images.all %}
        <span class="movie-image">
            <a href="{% url 'image' image.id %}">
                <img src="{{ image.image.url }}" alt="{{ image.description }}" width="150px">
            </a>
        </span>
    {% endfor %}
</div>
<div class="movie-details">
    <div class="movie-genres">
        <strong>Žánry:</strong>
        {% for genre in movie.genres.all %}
            <a href="{% url 'genre' genre.id %}">{{ genre }}</a>{% if not forloop.last %},{% endif %}
        {% empty %}
            Tento film nemá žádný žánr.
        {% endfor %}
    </div>

    <div class="movie-coutries">
        <strong>Země:</strong>
        {% for country in movie.countries.all %}
            {{ country }}{% if not forloop.last %},{% endif %}
        {% empty %}
            Tento film nemá žádnou zemi.
        {% endfor %}
    </div>

    <div class="movie-directors">
        <strong>Režie:</strong>
        {% for creator in movie.directors.all %}
            <a href="{% url 'creator' creator.id %}">{{ creator }}</a>{% if not forloop.last %},{% endif %}
        {% empty %}
            Tento film nemá žádného režiséra.
        {% endfor %}
    </div>

    <div class="movie-actors">
        <strong>Hrají:</strong>
        {% for creator in movie.actors.all %}
            <a href="{% url 'creator' creator.id %}">{{ creator }}</a>{% if not forloop.last %},{% endif %}
        {% empty %}
            Tento film nemá žádného herce.
        {% endfor %}
    </div>

    <div class="movie-length">
        <strong>Délka:</strong> {{ movie.length_format }}
    </div>

    <div class="movie-released">
        <strong>Rok:</strong> {{ movie.released }}
    </div>

    <div class="movie-rating">
        <strong>Hodnocení:</strong> {{ movie.rating }}
    </div>

    <div class="movie-description">
        <strong>Popis:</strong> {{ movie.description }}
    </div>

    {% if perms.viewer.change_movie %}
        <a href="{% url 'movie_update' movie.id %}" class="btn btn-primary">Aktualizovat</a>
    {% endif %}
    {% if perms.viewer.delete_movie %}
        <a href="{% url 'movie_delete' movie.id %}" class="btn btn-danger">Smazat</a>
    {% endif %}

    {% if request.user.is_authenticated %}
        <hr>
        <form action="" method="post">
            {% csrf_token %}
            <table>{{ form_review }}</table>
            <button type="submit">Odeslat</button>
        </form>
    {% endif %}

    {% if movie.reviews.all %}
        <div class="movie-reviews">
            {% for review in movie.reviews.all %}
                <div class="movie-review bg-light rounded mt-2 p-2 position-relative">
                    <div class="movie-review-user-box">
                        <span class="movie-review-user">
                            Uživatel: {{ review.user }}
                        </span>
                        <span class="movie-review-created font-italic text-secondary">
                            {{ review.created|date:'d. m. Y H:i' }}
                        </span>
                        {% if review.updated != review.created %}
                            <span class="movie-review-updated font-italic text-secondary">
                                (edit {{ review.updated|date:'d. m. Y H:i' }})
                            </span>
                        {% endif %}
                    </div>
                    <div class="movie-review-rating">
                        Hodnocení: {{ review.rating }}
                    </div>
                    <div class="movie-review-text">
                        Komentář: {{ review.text }}
                    </div>
                    {% if request.user == review.user.user %}
                        <a href="{% url 'review_delete' review.id %}" class="position-absolute" style="top: 10px; right: 10px;">❌</a>
                    {% endif %}
                </div>
            {% endfor %}
        </div>
    {% endif %}
</div>
{% endblock %}

viewer/templates/movies.html
{% extends "base.html" %}

{% block content %}
    Filtr dle žánru: <a href="{% url 'movies' %}">Všechny</a>,
    {% for genre in genres %}
        {% if genre.movies.count %}
            <a href="{% url 'genre' genre.id %}">{{ genre }} ({{ genre.movies.count }})</a>{% if not forloop.last %}, {% endif %}
        {% endif %}
    {% endfor %}
    <br>

    Filtr dle země: <a href="{% url 'movies' %}">Všechny</a>,
    {% for country in countries %}
        {% if country.movies.count %}
            <a href="{% url 'country' country.id %}">{{ country }} ({{ country.movies.count }})</a>
        {% endif %}
    {% endfor %}
    <h1>
        Filmy
        {% if genre %}
            žánru {{ genre }}
        {% endif %}
        {% if country %}
            země {{ country }}
        {% endif %}
    </h1>
        <ul>
            {% for movie in movies %}
                <li><a href="{% url 'movie' movie.id %}">{{ movie }}</a>
                    {% if perms.viewer.change_movie %}
                        <a href="{% url 'movie_update' movie.id %}">✏️</a>
                    {% endif %}
                    {% if perms.viewer.delete_movie %}
                        <a href="{% url 'movie_delete' movie.id %}">❌</a>
                    {% endif %}
                </li>
            {% endfor %}
        </ul>
{% endblock %}

viewer/templates/profiles.html
{% extends "base.html" %}

{% block content %}
    <h1>Profily</h1>
        <ul>
        {% for profile in profiles %}
            <li> {{ profile }}
            </li>
        {% endfor %}
        </ul>
{% endblock %}

viewer/templates/search.html
{% extends 'base.html' %}

{% block title %}Výsledky vyhledávání výrazu: '{{ search }}'{% endblock %}

{% block content %}
<h1>Výsledky vyhledávání výrazu: '{{ search }}'</h1>
    {% if movies_title_orig %}
        <h2>Výsledky pro originální název</h2>
        <ul>
          {% for movie in movies_title_orig %}
            <li><a href="{% url 'movie' movie.id %}">{{ movie.title_orig }}</a></li>
          {% endfor %}
        </ul>
    {% endif %}
    {% if movies_title_cz %}
        <h2>Výsledky pro český název</h2>
        <ul>
          {% for movie in movies_title_cz %}
            <li><a href="{% url 'movie' movie.id %}">{{ movie.title_cz }}</a></li>
          {% endfor %}
        </ul>
    {% endif %}
    {% if movies_descr %}
        <h2>Výsledky pro popis filmu</h2>
        <ul>
          {% for movie in movies_descr %}
            <li><a href="{% url 'movie' movie.id %}">{{ movie.title_orig }}</a></li>
          {% endfor %}
        </ul>
    {% endif %}
    {% if creator_names %}
        <h2>Výsledky pro jméno tvůrce</h2>
        <ul>
          {% for creator in creator_names %}
            <li><a href="{% url 'creator' creator.id %}">{{ creator.name }} {{ creator.surname }}</a></li>
          {% endfor %}
        </ul>
    {% endif %}
    {% if creator_surnames %}
        <h2>Výsledky pro příjmení tvůrce</h2>
        <ul>
          {% for creator in creator_surnames %}
            <li><a href="{% url 'creator' creator.id %}">{{ creator.name }} {{ creator.surname }}</a></li>
          {% endfor %}
        </ul>
    {% endif %}
    {% if g_json %}
        <h2>Výsledky pro vyhledávání na <a href="https://www.csfd.cz/">čsfd.cz</a></h2>
        <ul>
          {% for g_result in g_json.items %}
              <li><a href="{{ g_result.link }}">{{ g_result.title }}</a> <br>
                  {{ g_result.snippet }}</li>
          {% endfor %}
        </ul>
    {% endif %}
{% endblock %}