hollymovies/urls.py
from django.conf.urls.static import static
from django.contrib import admin
#from django.contrib.auth.views import LoginView
from django.urls import path, include

from api.views import *
from accounts.views import SignUpView, user_logout
from hollymovies import settings
from viewer.views import home, MoviesListView, \
    CreatorsListView, creator, GenreView, CountryView, CreatorCreateView, CreatorUpdateView, \
    CreatorDeleteView, MovieCreateView, MovieUpdateView, MovieDeleteView, GenreCreateView, GenreUpdateView, \
    GenreDeleteView, CountryCreateView, CountryUpdateView, CountryDeleteView, GenresListView, CountriesListView, \
    ProfilesListView, ImageCreateView, ImageDetailView, ImagesListView, ImageUpdateView, ImageDeleteView, \
    MovieTemplateView, ReviewDeleteView, search

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),

    path('', home, name='home'),

    path('movies/', MoviesListView.as_view(), name='movies'),
    path('movie/create/', MovieCreateView.as_view(), name='movie_create'),
    path('movie/update/<pk>/', MovieUpdateView.as_view(), name='movie_update'),
    path('movie/delete/<pk>/', MovieDeleteView.as_view(), name='movie_delete'),
    path('movie/<pk>/', MovieTemplateView.as_view(), name='movie'),

    path('creators/', CreatorsListView.as_view(), name='creators'),
    path('creator/create/', CreatorCreateView.as_view(), name='creator_create'),
    path('creator/update/<pk>/', CreatorUpdateView.as_view(), name='creator_update'),
    path('creator/delete/<pk>/', CreatorDeleteView.as_view(), name='creator_delete'),
    path('creator/<pk>/', creator, name='creator'),

    path('gernes/', GenresListView.as_view(), name='genres'),
    path('genre/create/', GenreCreateView.as_view(), name='genre_create'),
    path('genre/update/<pk>/', GenreUpdateView.as_view(), name='genre_update'),
    path('genre/delete/<pk>/', GenreDeleteView.as_view(), name='genre_delete'),
    path('genre/<pk>/', GenreView.as_view(), name='genre'),

    path('countries/', CountriesListView.as_view(), name='countries'),
    path('country/create/', CountryCreateView.as_view(), name='country_create'),
    path('country/update/<pk>/', CountryUpdateView.as_view(), name='country_update'),
    path('country/delete/<pk>/', CountryDeleteView.as_view(), name='country_delete'),
    path('country/<pk>/', CountryView.as_view(), name='country'),

    path('images/', ImagesListView.as_view(), name='images'),
    path('image/create/', ImageCreateView.as_view(), name='image_create'),
    path('image/update/<pk>/', ImageUpdateView.as_view(), name='image_update'),
    path('image/delete/<pk>/', ImageDeleteView.as_view(), name='image_delete'),
    path('image/<pk>/', ImageDetailView.as_view(), name='image'),

    path('review/delete/<pk>/', ReviewDeleteView.as_view(), name='review_delete'),

    path('search/', search, name='search'),

    path('profiles/', ProfilesListView.as_view(), name='profiles'),

    #path('accounts/login/', LoginView.as_view(), name='login'),
    path('accounts/signup/', SignUpView.as_view(), name='signup'),
    path('accounts/logout/', user_logout, name='logout'),
    path('accounts/', include('django.contrib.auth.urls')),  # defaultní paths a veiws z Djanga

    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api/movies/', Movies.as_view(), name='api_movies'),
    path('api/movie/<pk>/', MovieDetail.as_view(), name='api_movie'),
    path('api/creators/', Creators.as_view(), name='api_creators'),
    path('api/creator/<pk>/', CreatorDetail.as_view(), name='api_creator'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

viewer/models.py
from datetime import date

from django.db.models import *  # Model, CharField, DateField, ForeignKey, SET_NULL, TextField, ManyToManyField, IntegerField

from accounts.models import Profile


class Genre(Model):
    name = CharField(max_length=20, null=False, blank=False, unique=True)

    class Meta:
        ordering = ['name']

    def __repr__(self):
        return f"Genre(name={self.name})"

    def __str__(self):
        return f"{self.name}"


class Country(Model):
    name = CharField(max_length=64, null=False, blank=False, unique=True)
    code = CharField(max_length=3, null=False, blank=False, unique=True)

    class Meta:
        verbose_name_plural = "Countries"
        ordering = ['name']

    def __repr__(self):
        return f"Country(name={self.name}, code={self.code})"

    def __str__(self):
        return f"{self.name}"


class Creator(Model):
    name = CharField(max_length=32, null=True, blank=True)
    surname = CharField(max_length=32, null=True, blank=True)
    date_of_birth = DateField(null=True, blank=True)
    date_of_death = DateField(null=True, blank=True)
    country_of_birth = ForeignKey(Country, null=True, blank=True, on_delete=SET_NULL, related_name='creators_born')
    country_of_death = ForeignKey(Country, null=True, blank=True, on_delete=SET_NULL, related_name='creators_died')
    biography = TextField(null=True, blank=True)
    created = DateTimeField(auto_now_add=True)
    updated = DateTimeField(auto_now=True)

    class Meta:
        ordering = ['surname', 'name']

    def __repr__(self):
        return f"Creator(name={self.name}, surname={self.surname})"

    def __str__(self):
        return f"{self.name} {self.surname}"

    def age(self):
        if self.date_of_birth:
            end_date = date.today()
            if self.date_of_death:
                end_date = self.date_of_death
            return (end_date.year - self.date_of_birth.year -
                    ((end_date.month, end_date.day) < (self.date_of_birth.month, self.date_of_birth.day)))
        return None


class Movie(Model):
    title_orig = CharField(max_length=150, null=False, blank=False)  # https://en.wikipedia.org/wiki/Night_of_the_Day_of_the_Dawn_of_the_Son_of_the_Bride_of_the_Return_of_the_Revenge_of_the_Terror_of_the_Attack_of_the_Evil,_Mutant,_Alien,_Flesh_Eating,_Hellbound,_Zombified_Living_Dead
    title_cz = CharField(max_length=150, null=True, blank=True)
    genres = ManyToManyField(Genre, blank=True, related_name='movies')
    countries = ManyToManyField(Country, blank=True, related_name='movies')
    actors = ManyToManyField(Creator, blank=True, related_name='acting')
    directors = ManyToManyField("viewer.Creator", blank=True, related_name='directing')
    length = IntegerField(null=True, blank=True)  # min
    released = IntegerField(null=True, blank=True)  # year
    description = TextField(null=True, blank=True)
    rating = FloatField(null=True, blank=True)  # 0-100
    created = DateTimeField(auto_now_add=True)
    updated = DateTimeField(auto_now=True)

    class Meta:
        ordering = ['title_orig', 'released']

    def __repr__(self):
        return f"Movie(title_orig={self.title_orig})"

    def __str__(self):
        return f"{self.title_orig} ({self.released})"

    def length_format(self):
        hours = self.length // 60
        minutes = self.length % 60
        if minutes < 10:
            minutes = f"0{minutes}"
        return f"{hours}:{minutes}"


class Image(Model):
    image = ImageField(upload_to='images/', default=None, null=False, blank=False)
    movie = ForeignKey(Movie, on_delete=SET_NULL, null=True, blank=True, related_name='images')
    actors = ManyToManyField(Creator, blank=True, related_name='images')
    description = TextField(null=True, blank=True)

    def __repr__(self):
        return f"Image(image={self.image}, movie={self.movie}, actors={self.actors}, description={self.description})"

    def __str__(self):
        return f"Image: {self.image}, {self.description}"


class Review(Model):
    movie = ForeignKey(Movie, on_delete=CASCADE, null=False, blank=False, related_name='reviews')
    user = ForeignKey(Profile, on_delete=SET_NULL, null=True, blank=False, related_name='reviews')
    rating = IntegerField(null=True, blank=True)
    text = TextField(null=True, blank=True)
    created = DateTimeField(auto_now_add=True)
    updated = DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-updated']

    def __repr__(self):
        return (f"Review(movie={self.movie}, user={self.user}, "
                f"rating={self.rating}, text={self.text})")

    def __str__(self):
        return f"User: {self.user}, movie:{self.movie}, rating={self.rating}, text={self.text[:50]}"

templates/base.html
<!DOCTYPE html>
{% load static %}

<html {% if LANGUAGE_CODE %}
      lang="{{ LANGUAGE_CODE }}"
      {% else %}
      lang="en"
      {% endif %}
>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
          integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"
            integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"
            integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
            crossorigin="anonymous"></script>
</head>

<body>

{% include "navbar.html" %}

<div class="container">
    <div class="jumbotron">
        {% block content %}{% endblock %}
    </div>
</div>

{% include "footer.html" %}

</body>

</html>

templates/footer.html
<footer class="text-center text-white bg-dark p-4" >
        <a class="text-reset fw-bold" href="https://sdacademy.cz/">SDAcademy</a>
        - PythonRemoteCZ23
        - Backend technologies
</footer>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container fixed">
        <a class="navbar-brand" href="/">HollyMovies</a>
        <button
                class="navbar-toggler" type="button"
                data-toggle="collapse" data-target="#navbarNavAltMarkup"
        >
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-item nav-link active" href="{% url 'home' %}">Domů</a>
                <a class="nav-item nav-link active" href="{% url 'movies' %}">Filmy</a>
                <a class="nav-item nav-link active" href="{% url 'creators' %}">Tvůrci</a>

                {% comment "TODO: actors"%}
                <a class="nav-item nav-link active" href="{% url 'actors' %}">Herci</a>
                {% endcomment %}

            </div>

            <div class="navbar-nav">
                <div class="nav-item dropdown">
                    {% if perms.viewer.add_creator or perms.viewer.add_movie %}
                        <a class="nav-link active dropdown-toggle" href="#" data-toggle="dropdown">
                            Přidat
                        </a>
                        <div class="dropdown-menu">
                            {% if perms.viewer.add_creator %}
                                <a class="dropdown-item" href="{% url 'creator_create' %}">tvůrce</a>
                            {% endif %}
                            {% if perms.viewer.add_movie %}
                                <a class="dropdown-item" href="{% url 'movie_create' %}">film</a>
                            {% endif %}
                            {% if perms.viewer.add_image %}
                                <a class="dropdown-item" href="{% url 'image_create' %}">obrázek</a>
                            {% endif %}
                            {% if perms.viewer.add_genre %}
                                <a class="dropdown-item" href="{% url 'genre_create' %}">žánr</a>
                            {% endif %}
                            {% if perms.viewer.add_country %}
                                <a class="dropdown-item" href="{% url 'country_create' %}">zemi</a>
                            {% endif %}
                        </div>
                    {% endif %}
                </div>
            </div>

            <div class="navbar-nav">
                <div class="nav-item dropdown">
                    {% if user.is_staff %}
                        <a class="nav-link active dropdown-toggle" href="#" data-toggle="dropdown">
                            ADMIN
                        </a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="{% url 'admin:index' %}">admin</a>
                            {% if perms.viewer.view_genres %}
                                <a class="dropdown-item" href="{% url 'genres' %}">seznam žánrů</a>
                            {% endif %}
                            {% if perms.viewer.view_countries %}
                                <a class="dropdown-item" href="{% url 'countries' %}">seznam zemí</a>
                            {% endif %}
                            {% if perms.viewer.view_images %}
                                <a class="dropdown-item" href="{% url 'images' %}">seznam obrázků</a>
                            {% endif %}
                            {% if perms.viewer.view_profiles %}
                                <a class="dropdown-item" href="{% url 'profiles' %}">seznam profilů</a>
                            {% endif %}
                        </div>
                    {% endif %}
                </div>
            </div>

            <div class="navbar-nav">
                <div class="nav-item dropdown">
                    {% if user.is_staff %}
                        <a class="nav-link active dropdown-toggle" href="#" data-toggle="dropdown">
                            API
                        </a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="{% url 'api_movies' %}">filmy</a>
                            <a class="dropdown-item" href="{% url 'api_creators' %}">tvůrci</a>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>

        <div class="navbar-nav ml-auto">
            <div id="search">
                <form method="post" action="/search/">
                    {% csrf_token %}
                    {% comment %}<label for="search" class="text-light">Search:</label> {% endcomment %}
                    <input type="text" id="search" name="search" placeholder="🔎 Hledej...">
                </form>
            </div>
        </div>

        <div class="navbar-nav ml-auto">
            <div class="nav-item dropdown">
                {% if user.is_authenticated %}
                    <a class="nav-link active dropdown-toggle" href="#" data-toggle="dropdown">
                        {{ user.username }}
                    </a>
                    <div class="dropdown-menu dropdown-menu-right">
                        <a class="dropdown-item text-right" href="{% url 'logout' %}">Odhlásit</a>
                        <a class="dropdown-item text-right" href="{% url 'password_change' %}">Změnit heslo</a>
                        <a class="dropdown-item text-right" href="{% url 'password_reset' %}">Resetovat heslo</a>
                    </div>
                {% else %}
                    <a class="nav-link active dropdown-toggle" href="#" data-toggle="dropdown">
                        Nepřihlášený uživatel.
                    </a>
                    <div class="dropdown-menu dropdown-menu-right">
                        <a class="dropdown-item text-right" href="{% url 'login' %}">Přihlásit</a>
                        <a class="dropdown-item text-right" href="{% url 'signup' %}">Registrovat</a>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
</nav>